---
title: "Perform_umap_for_SYNGENE_Fig4H"
author: "Florian Heigwer"
date: "8/6/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyr)
library(readr)
library(kernlab)
library(pryr)
library(LMGene)
library(gridExtra)
library(umap)
library(uwot)
library(ggplot2)
library(ggpubr)
library(RPostgreSQL)
library(ggrastr)

theme_b110<-function(){
  theme_classic() +
  theme(
    axis.text=element_text(size = 10), 
    axis.title=element_text(size = 10),
    plot.title = element_text(size = 12,hjust = 0.5,face="bold"),
    legend.title = element_text(size = 12),
    legend.text = element_text(size =10),
    legend.position = "bottom"
    )
}

sgi_blue    = '#5087C8'
sgi_yellow1 = '#F2EE35'
sgi_yellow2 = '#FED98E'
b110_grey   = '#808080'
b110_grey_light   = '#909090'
google_red='#dd4b39'
google_green='#0F9D58'
google_yellow='#F4B400'
google_blue='#4285F4'

```

## Get new data

```{r get data, eval=FALSE, message=FALSE, warning=FALSE, include=FALSE}
test_db <- src_postgres(
  dbname = "incell2000_test",
  host = "b110-sc2sn01",
  user = "florianH",
  password = "x!Kl9R_p7XZYjLhg"
)

screen_annotation <- tbl(test_db,"screenings_screening")

screens <- screen_annotation %>% 
  filter(query_name %in% c("brm","B52","piwi","Cdc23","Rab1","Cdk2","RLUC")) %>%
  select(plate_barcode,query_name) %>%
  collect() %>%
  extract(plate_barcode,"screen",".*_(\\w+)") %>%
    filter(screen!="S001")

plate_annotation <- tbl(test_db,"D1086_annotation")

#plate_well <- 
  
plate_well <- plate_annotation %>% 
  filter(hd3gene %in% c("S6k","Spindly","geminin","AP-1-2beta","AP-2sigma","AP-2mu","CSN3","Cdk1","Rheb","CG2807") | gene_symbol=="AP-2mu",
         plate!="CTRL1",plate!="CTRL2") %>%
  collect() %>%
    select(plate,well,gene_symbol,hd3gene)


screen_array <- screens %>% pull(screen)
plate_array <- plate_well %>% pull(plate)
well_array <-  plate_well %>% pull(well) %>% unique() %>% c(.,"P07")

relevant_combinations <- 
  tibble(screenx = c("S095","S095","S097","S097","S170","S170","S172","S172","S201","S201","S203","S203","S120","S120","S122","S122","S169","S169","S171","S171","S188","S188","S186","S186","S188","S188","S186","S186","S188","S188","S186","S186"),
         platex =  c("1013","2013","1013","2013","1018","2018","1018","2018","1011","2011","1011","2011","1016","2016","1016","2016","1013","2013","1013","2013","1011","2011","1011","2011","1019","2019","1019","2019","1019","2019","1019","2019"),
         wellx=    c("J17","J17","J17","J17","D18","D18","D18","D18","G22","G22","G22","G22","P16","P16","P16","P16","D22","D22","D22","D22","I14","I14","I14","I14","J22","J22","J22","J22","H17","H17","H17","H17") )

ll <- as.list(1:nrow(relevant_combinations))

example_sc_data<-lapply(ll, function(x){
  print(x)
  screenx <- relevant_combinations %>% pull(screenx) %>% .[x]
  platex <- relevant_combinations %>% pull(platex) %>% .[x]
  wellx <- relevant_combinations %>% pull(wellx) %>% .[x]
    
  example_sc_data <- tbl(test_db,"D1086_single_cell_V1") %>%
    filter(screen == screenx,
           plate == platex,
           well == wellx
           ) %>%
    collect(n=Inf)
  
  return(example_sc_data)
}) %>% bind_rows()

saveRDS(example_sc_data,"objects/relevant_sc_feature_data.rds")
write_delim(example_sc_data,"objects/relevant_sc_feature_data.txt",delim = "\t")


example_sc_class<-lapply(ll, function(x){
  print(x)
  screenx <- relevant_combinations %>% pull(screenx) %>% .[x]
  platex <- relevant_combinations %>% pull(platex) %>% .[x]
  wellx <- relevant_combinations %>% pull(wellx) %>% .[x]
    
  example_sc_classx <- tbl(test_db,"D1086_syngene_classified_cells_sc") %>%
    filter(screen == screenx,
           plate == platex,
           well == wellx
           ) %>%
    collect(n=Inf)
  
  return(example_sc_classx)
}) %>% bind_rows()

saveRDS(example_sc_class,"objects/relevant_sc_class.rds")
write_delim(example_sc_class,"objects/relevant_sc_class.txt",delim = "\t")

```

## Normalize data


```{r normalize and subsample data, echo=FALSE}

# Annotation query genes

query_genes_ann <- readRDS("objects/query_genes.rds")

# Annotation target genes

load("objects/updated_target_genes.RData")


load("objects/umap_theme.RData")

#Theme for bar plots

load("objects/bar_plot_theme.RData")

#Colours used for the plots

load("objects/colour_codes.RData")

#Scale factors to normalise features.

load("objects/scale_factors.rdata")

#Important features used in the UMAPs

imp_features <- readRDS("objects/imp_features.rds")

#Function to normalise the feature values using the screen scale factors

data_normalization <- function(value, median, mad){
  
  return((glog(value, lambda = 1)-median)/mad)
  
}

sample_class <- readRDS("objects/relevant_sc_class.rds")

sample_data <- readRDS("objects/relevant_sc_feature_data.rds") %>% 
                left_join(query_genes_ann %>% 
                            separate(plate_barcode, into= c("c", "screen"), sep = "_") %>% 
                            select(screen, query_name)) %>% 
                left_join(target_genes_new %>% unite("plate",replicate, plate, sep = "") %>% 
                            select(plate, well, gene_symbol)) %>% 
                dplyr::rename(target_name = gene_symbol) %>% 
                select(screen, plate, well, field, query_name, target_name,
                       everything()) %>% as_tibble() %>%
                left_join(sample_class %>% mutate(field=as.numeric(field))) %>% 
                drop_na() %>%
                separate(label, into = c("context", "group"), sep = "_", extra = "merge")

rluc_data <- readRDS("objects/rluc_single_cells.rds") %>% 
              separate(label, into = c("context", "group"), sep = "_", extra = "merge") %>% 
              mutate(query_name = rep("RLUC"),
                     target_name = rep("RLUC"))



```

#Normalise features

Before embedding single cells I will normalize the feature values

```{r}

list_norm_data <- list()

for (screen_name in c("S100", "S122", "S152")){
  
  data <- rluc_data %>% filter(screen == screen_name)
  
  for (feature in imp_features){
        
    if(list_mads[[screen_name]][[feature]] != 0){
          
      data[feature] <- data_normalization(data[[feature]], list_medians[[screen_name]][[feature]],
                                            list_mads[[screen_name]][[feature]])
          
    }else{data[feature] <- glog(data[[feature]], lambda =  1)}
  }
  
  list_norm_data[[screen_name]] <- data
  
}

rluc_data <- do.call("rbind", list_norm_data)

list_norm_data <- list()

for (screen_name in c(sample_data %>% pull(screen) %>% unique())){
  
  data <- sample_data %>% filter(screen == screen_name)
  
  for (feature in imp_features){
        
    if(list_mads[[screen_name]][[feature]] != 0){
          
      data[feature] <- data_normalization(data[[feature]], list_medians[[screen_name]][[feature]],
                                            list_mads[[screen_name]][[feature]])
          
    }else{data[feature] <- glog(data[[feature]], lambda = 1)}
  }
  
  list_norm_data[[screen_name]] <- data
  
}

sample_data <- do.call("rbind", list_norm_data)

sample_data<-sample_data %>%
  select(one_of(names(rluc_data)))

```

```{r}
#umap_layout_rluc <- sample_data %>% 
#                    group_by(well) %>%
#                    sample_n(5000) %>%
#                    ungroup() %>%
#                    select(-field) %>%
                    #filter(context == "Isolated") %>% 
#                     select_if(is.numeric) %>% 
#                      uwot::umap(#n_neighbors = 30,
#                                 ret_model = T,fast_sgd = TRUE)

#save(umap_layout_rluc, file = "objects/umap_layout_rluc.RData")

 load("objects/umap_layout_rluc.RData")
```

##RLUC isolated

Here I will make a UMAP of 10000 random RLUC isolated cells. 

```{r}

rluc_iso_sample <- sample_n(rluc_data, 4000, replace = F)

umap_rluc_iso <- rluc_iso_sample %>% select_if(is.numeric) %>% 
                  umap_transform(model = umap_layout_rluc) %>% 
                  as.data.frame() %>% dplyr::rename(dimension1 = V1, dimension2 = V2) %>% 
                  mutate(group = rluc_iso_sample %>% pull(group))

umap_rluc_plot <-  print(ggplot(umap_rluc_iso, aes(x=-dimension1, y= -dimension2, 
                                                color = factor(group)))+
                            geom_point_rast(size = 1.5,raster.dpi = 600)+
                            umap_theme()+
                           theme_b110()+ 
                           theme(
                            legend.title = element_blank())+
                            scale_color_manual(values = c(google_green, lacoste_green,
                                                          google_yellow, 
                                                          google_red, google_blue), 
                                               labels = c("Big", "Condensed", "Elongated",
                                                          "Irregular nucleus", "Normal"))+
                            guides(colour = guide_legend(nrow = 2, byrow = T, 
                                                         override.aes = list(size = 6)))+
                            xlab("UMAP dimension 1")+
                            ylab("UMAP dimension 2"))+
                              ylim(c(-4,4))+
                              xlim(c(-6,6)) 

ggsave(umap_rluc_plot, height = 7, width = 7.5, 
       filename = "graphics/umap_all_rluc_0.3.pdf")

ggsave(umap_rluc_plot, height = 7, width = 7.5, 
       filename = "graphics/umap_all_rluc_0.3.png")


rluc_grp_prop <- rluc_iso_sample %>% group_by(group) %>% tally() %>% 
                  mutate(prop = n/sum(n), context = rep("Isolated"),
                         group = factor(group, levels = c("Elongated", "Irregular_nucleus", 
                                                          "Condensed", "Big", "Normal")))

bar_plot_iso_rluc <- print(ggplot(rluc_grp_prop, 
                                    aes(x = context, y = prop*100, 
                                        fill = group))+
                                geom_bar(stat = "identity", position = "stack")+
                                bar_plot_theme()+
                                scale_y_continuous(expand = c(0,0), limits = c(0,101))+
                                scale_x_discrete(expand = c(0,0))+
                                theme(legend.title = element_blank(),
                                      legend.position = "none",
                                      plot.title = element_blank(), 
                                      axis.text.x = element_blank(), 
                                      axis.ticks.x = element_blank())+
                                guides(fill=guide_legend(nrow=3,byrow=TRUE))+
                                scale_fill_manual(values = c(google_yellow,
                                                             google_red,lacoste_green,
                                                              google_green,
                                                              google_blue))+
                                geom_text(data = rluc_grp_prop  %>% filter(prop >0.04), 
                                           aes(label = round(prop*100, 1)),
                                           position = position_stack(vjust = .5), 
                                          colour = "white", size = 7)+
                                ylab("Percentage of cells (%)"))

arranged_rluc <- ggarrange(umap_rluc_plot,bar_plot_iso_rluc, ncol = 2, widths = c(5,1))

arranged_rluc_tit <- annotate_figure(arranged_rluc, top = text_grob("RLUC RNAi: Isolated cells", 
                                                                size = 26, hjust = 0.5))

ggsave(arranged_rluc_tit, filename = "graphics/umap_rluc_barplot.png", height = 9, width = 10)
ggsave(arranged_rluc_tit, filename = "graphics/umap_rluc_barplot.pdf", height = 9, width = 10)

```


## All other samples isolated

Here I will make a UMAP of 30 % random  isolated cells. 

```{r}

plot_Stuff <- function(screenx,platex,wellx){
  
 #rluc_iso_sample <- sample_frac(sample_data %>% filter(screen==screenx,plate==platex,well==wellx), 0.3, replace = F) #context == "Isolated",
  
  rluc_iso_sample <- sample_data %>% filter(screen==screenx,plate==platex,well==wellx) #context == "Isolated",
 
  umap_rluc_iso <- rluc_iso_sample %>% select_if(is.numeric) %>% select(-field) %>%
                    umap_transform(model = umap_layout_rluc) %>% 
                    as.data.frame() %>% dplyr::rename(dimension1 = V1, dimension2 = V2) %>% 
                    mutate(group = rluc_iso_sample %>% pull(group))
  
  umap_rluc_plot <-  ggplot(umap_rluc_iso, aes(x=-dimension1, y= -dimension2, 
                                                  color = factor(group)))+
                              geom_point_rast(size = 1.5,raster.dpi = 600)+
                              umap_theme()+
                             theme_b110()+ 
                             theme(
                              legend.title = element_blank())+
                              scale_color_manual(values = c(google_green, lacoste_green,
                                                            google_yellow, 
                                                            google_red, google_blue), 
                                                 labels = c("Big", "Condensed", "Elongated",
                                                            "Irregular nucleus", "Normal"))+
                              guides(colour = guide_legend(nrow = 2, byrow = T, 
                                                           override.aes = list(size = 6)))+
                              xlab("UMAP dimension 1")+
                              ylab("UMAP dimension 2") +
                              ylim(c(-4,4))+
                              xlim(c(-6,6)) +
                              ggtitle(paste0(rluc_iso_sample$query_name[1],"_x_",rluc_iso_sample$target_name[1] ))
  
  
  rluc_grp_prop <- rluc_iso_sample %>% group_by(group) %>% tally() %>% 
                    mutate(prop = n/sum(n), context = rep("Isolated"),
                           group = factor(group, levels = c("Elongated", "Irregular_nucleus", 
                                                            "Condensed", "Big", "Normal")))
  
  bar_plot_iso_rluc <- ggplot(rluc_grp_prop, 
                                      aes(x = context, y = prop*100, 
                                          fill = group))+
                                  geom_bar(stat = "identity", position = "stack")+
                                  bar_plot_theme()+
                                  scale_y_continuous(expand = c(0,0), limits = c(0,101))+
                                  scale_x_discrete(expand = c(0,0))+
                                  theme(legend.title = element_blank(),
                                        legend.position = "none",
                                        plot.title = element_blank(), 
                                        axis.text.x = element_blank(), 
                                        axis.ticks.x = element_blank())+
                                  guides(fill=guide_legend(nrow=3,byrow=TRUE))+
                                  scale_fill_manual(values = c(google_yellow,
                                                               google_red,lacoste_green,
                                                                google_green,
                                                                google_blue))+
                                  geom_text(data = rluc_grp_prop  %>% filter(prop >0.04), 
                                             aes(label = round(prop*100, 1)),
                                             position = position_stack(vjust = .5), 
                                            colour = "white", size = 7)+
                                  ylab("Percentage of cells (%)")
  
  arranged_rluc <- ggarrange(umap_rluc_plot,bar_plot_iso_rluc, ncol = 2, widths = c(5,1))
  
  arranged_rluc_tit <- annotate_figure(arranged_rluc, top = text_grob("RLUC RNAi: Isolated cells", 
                                                                  size = 26, hjust = 0.5))
  
  ggsave(arranged_rluc_tit, filename = paste0("graphics/umap_barplot_",screenx,"_",platex,"_",rluc_iso_sample$query_name[1],"_x_",rluc_iso_sample$target_name[1],".pdf"), height = 9, width = 10)
  ggsave(arranged_rluc_tit, filename = paste0("graphics/umap_barplot_",screenx,"_",platex,"_",rluc_iso_sample$query_name[1],"_x_",rluc_iso_sample$target_name[1],".png"), height = 9, width = 10)

}

relevant_combinations <- 
  tibble(screenx = c("S095","S095","S097","S097","S170","S170","S172","S172","S201","S201","S203","S203","S120","S120","S122","S122","S169","S169","S171","S171","S188","S188","S186","S186","S188","S188","S186","S186","S188","S188","S186","S186"),
         platex =  c("1013","2013","1013","2013","1018","2018","1018","2018","1011","2011","1011","2011","1016","2016","1016","2016","1013","2013","1013","2013","1011","2011","1011","2011","1019","2019","1019","2019","1019","2019","1019","2019"),
         wellx=    c("J17","J17","J17","J17","D18","D18","D18","D18","G22","G22","G22","G22","P16","P16","P16","P16","D22","D22","D22","D22","I14","I14","I14","I14","J22","J22","J22","J22","H17","H17","H17","H17") )

for(i in 1:nrow(relevant_combinations)){ 
    plot_Stuff( 
      screenx = relevant_combinations %>% pull(screenx) %>% .[i],
      platex = relevant_combinations %>% pull(platex) %>% .[i],
      wellx = relevant_combinations %>% pull(wellx) %>% .[i]
      )
}

```



