---
title: "Figure_supplement"
output: html_document
editor_options: 
  chunk_output_type: console
---

## SETUP

```{r setup, include=FALSE}
library(tidyverse)
library(ggpubr)
library(ggrastr)
library(patchwork)
library(ggrepel)
library(MASS)

theme_b110<-function(){
  theme_classic() +
  theme(
    axis.text=element_text(size = 10), 
    axis.title=element_text(size = 10),
    plot.title = element_text(size = 12,hjust = 0.5,face="bold"),
    legend.title = element_text(size = 12),
    legend.text = element_text(size =10),
    legend.position = "bottom"
    )
}

sgi_blue    = '#5087C8'
sgi_yellow1 = '#F2EE35'
sgi_yellow2 = '#FED98E'
b110_grey   = '#808080'
b110_grey_light   = '#909090'
b110_transparent_black = alpha('#000000',0.5)
google_red='#dd4b39'
google_green='#0F9D58'
google_yellow='#F4B400'
google_blue='#4285F4'

```


```{r}
load("processed_data/statistically_tested_pi_cells.RData")
load("processed_data/filtered_data_cells.RData")
load("processed_data/normalized_data_cells.RData")

feature="nuclear count"

interac_sub<-interaction_stats %>% dplyr::select(gene_symbol,mpi,fdr,fbgn,targetid,target_main,query_main,query_name)

filtered_data_mean<-filtered_data %>% group_by(targetid,query_name) %>% summarise(value=mean(value,na.rm=T))

joined_sub<-filtered_data_mean %>% left_join(interac_sub)
```

# Figure S2 example interactions

```{r}
interaction_vecs <- readRDS("processed_data/interactions_stats_all_feats_df_18112019.rds")
interaction_stats <-interaction_vecs %>% filter(feature=="cells")

plot_example_interaction<-function(tgene="Rheb",qgene="raptor"){
  fb<-interaction_stats %>% filter(gene_symbol==tgene,query_name==qgene) %>% pull(targetid) %>% .[1]
  scores<-interaction_stats %>% filter(targetid==fb,query_name==qgene) %>% gather(pirep,piscore,`1`,`2`,`3`,`4`)
  
  piscore<- pull(scores,piscore)
  
  targetmain<-pull(scores,target_main)
  
  querymain<-pull(scores,query_main)
  
  target<-pull(scores,gene_symbol)
  
  double<-filtered_data %>% filter(targetid==fb,query_name==qgene) %>% pull(value)
  
  query<-filtered_data %>% filter(targetid==fb,query_name==qgene) %>% pull(query_name)
  
  GI_df<-
    cbind.data.frame(target,query,"t"=targetmain,"q"=querymain,"tq"=double,"pi"=piscore) %>% 
    mutate(e=targetmain+querymain) %>% 
    gather(category,value,-target,-query) %>% 
    distinct()
  

  GI_df %>% 
    mutate(category=factor(category,levels = c("t","q","e","tq","pi"))) %>%
    group_by(category) %>%
    mutate(m=mean(value,na.rm=T)) %>%
    ggplot(aes(x=category,y=m,fill=category)) +
    geom_bar(stat = "identity",position = "dodge") +
    geom_point(aes(y=value),pch=19,size=2,col=b110_grey) +
    geom_hline(yintercept = 0,lty=2) +
    ylab("interaction score [π]") +
    xlab("measurement") + 
    ggtitle(paste0(tgene,' + ',qgene)) +
    scale_fill_manual(values = c("t"=b110_grey_light,"q"=b110_grey_light,"e"=b110_grey_light,"tq"=b110_grey_light,"pi"=if(mean(piscore,na.rm = T)<0){google_blue}else{google_yellow})) +
    theme_b110()+ theme(legend.position = "none")
}

  # plot the raptor <-> Rheb interaction 

sl2<-plot_example_interaction(tgene = "Rheb",qgene = "Tor")
resc2<-plot_example_interaction(tgene = "Tsc1",qgene = "raptor")

  # plot the Tsc1 <-> raptor interaction 
sl<-plot_example_interaction(tgene = "Sos",qgene = "Stat92E")

resc<-plot_example_interaction(tgene = "RasGAP1",qgene = "pnt")

cand<-plot_example_interaction(tgene = "sqd",qgene = "Tor")

resc3<-plot_example_interaction(tgene = "Diap1",qgene = "Dronc")


ggsave("plots/S_viab_example_interactions_Tor_Diap_viab.pdf",sl+resc+cand +resc2+sl2+resc3+plot_layout(ncol = 2),width = 10,height = 24,units = 'cm')

ggsave("plots/S2_viab_example_interactions_Tor_Diap_viab.png",sl+resc+cand +resc2+sl2+resc3+plot_layout(ncol = 2),width = 10,height = 24,units = 'cm')


interaction_stats <-interaction_vecs %>% filter(feature=="actin.m.eccentricity.tmean")
load("processed_data/filtered_data_actin.m.eccentricity.tmean.RData")

sl2<-plot_example_interaction(tgene = "betaCOP",qgene = "Sec24CD")
resc2<-plot_example_interaction(tgene = "Nsf2",qgene = "Sesn")

  # plot the Tsc1 <-> raptor interaction 
sl<-plot_example_interaction(tgene = "Nsf2",qgene = "S6k")

resc<-plot_example_interaction(tgene = "RanBP3",qgene = "S6k")

cand<-plot_example_interaction(tgene = "alphaCOP",qgene = "mor")

resc3<-plot_example_interaction(tgene = "Pvf2",qgene = "Stat92E")


ggsave("plots/S2_eccentr_example_interactions_stuff.pdf",sl+resc+cand +resc2+sl2+resc3+plot_layout(ncol = 2),width = 10,height = 24,units = 'cm')

ggsave("plots/S2_eccentr_example_interactions_stuff.png",sl+resc+cand +resc2+sl2+resc3+plot_layout(ncol = 2),width = 10,height = 24,units = 'cm')
```

## Supplemental Figure S3

```{r}

significant_feature_interactions<-interaction_vecs %>% filter(fdr<0.2)

count_per_qf<-significant_feature_interactions %>% 
  mutate(feature=if_else(grepl("DNA.h.*",feature),"DNA.texture",feature)) %>%
  mutate(feature=if_else(grepl("actin.h.*",feature),"actin.texture",feature)) %>%
  mutate(feature=if_else(grepl("actin.[sm].*",feature),"actin.morphology",feature)) %>%
  mutate(feature=if_else(grepl("DNA.[sm].*",feature),"DNA.morphology",feature)) %>%
  mutate(direction=sign(mpi)) %>%
  filter(direction!=0) %>%
  mutate(sig=if_else(fdr<0.1,1,0)) %>%
  filter(sig==1) %>%
  group_by(query_name,feature) %>% 
  count() %>% 
  spread(feature,n,fill = 0) %>% 
  gather(feature,n,-query_name) %>%
  group_by(feature) %>%
  mutate(n=(n-mean(n))/sd(n)) %>%
  ungroup()

ordx<-count_per_qf  %>% arrange(feature) %>% spread(feature,n,fill = 0) %>% arrange(query_name) %>% dplyr::select(-query_name) %>% dist(method = "euclidean") %>% hclust(method = "ward.D2") %>% .$order
namesx<-count_per_qf  %>% arrange(feature) %>% spread(feature,n,fill = 0) %>% arrange(query_name) %>% pull(query_name) %>% .[ordx]

ordy<-count_per_qf  %>% arrange(query_name) %>% spread(query_name,n,fill = 0) %>% arrange(feature) %>% dplyr::select(-feature) %>% dist(method = "euclidean") %>% hclust(method = "ward.D2") %>% .$order
namesy<-count_per_qf  %>% arrange(query_name) %>% spread(query_name,n,fill = 0) %>% arrange(feature) %>% pull(feature) %>% .[ordy]

p<-count_per_qf %>%
  mutate(query_name=factor(query_name,levels = namesx),
         feature=factor(feature,levels = namesy)) %>%
  ggplot(aes(x=feature,y=query_name,fill=n)) + 
      geom_tile()+
  ylab("features") +
  xlab("query genes") +
  ggtitle("GI coutns per feature and query") +
  theme_b110() +
  scale_fill_gradient(low = "white",high = "black") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1), axis.text=element_text(size = 6)) 


ggsave("plots/S3_interaction_count_per_feature_and_query_heat.pdf",p,width = 4,height = 10)
ggsave("plots/S3_interaction_count_per_feature_and_query_heat.png",p,width = 4,height = 10)
```

