q---
title: "Figure_1"
output: html_document
editor_options: 
  chunk_output_type: console
---

## SETUP

```{r setup, include=FALSE}
library(tidyverse)
library(ggpubr)
library(patchwork)
library(ggrepel)
library(GGally)
library(MASS)
library(ggridges)
library(cowplot)
library("dendextend")
library(dtplyr)
library(corrr)
library(RColorBrewer)
library(ggrastr)
theme_set(theme_cowplot())

theme_b110<-function(){
  theme_classic() +
  theme(
    axis.text=element_text(size = 10), 
    axis.title=element_text(size = 10),
    plot.title = element_text(size = 12,hjust = 0.5,face="bold"),
    legend.title = element_text(size = 12),
    legend.text = element_text(size =10),
    legend.position = "bottom"
    )
}

sgi_blue    = '#5087C8'
sgi_yellow1 = '#F2EE35'
sgi_yellow2 = '#FED98E'
b110_grey   = '#808080'
b110_grey_light   = '#909090'
b110_transparent_black = alpha('#000000',0.5)
google_red='#dd4b39'
google_green='#0F9D58'
google_yellow='#F4B400'
google_blue='#4285F4'

```

## Figure 1 S1

Histograms showing the distributions of interactions along different example features

```{r}

usable_features<-readRDS("processed_data/usable_features_18112019.rds")
main_effects_df <- read_rds("processed_data/main_effect_df_181119.rds")
interaction_vecs<-read_rds("processed_data/interactions_stats_all_feats_df_18112019.rds")

load("processed_data/filtered_data_cells.RData")
load("processed_data/normalized_data_cells.RData")


```

# Figure 1A)  Plotting example of single vs. double mutant phenotypes

```{r, Figure_1_C_Example_gene_interactions}

interac_sub<-interaction_vecs %>% filter(feature=="cells")%>% dplyr::select(gene_symbol,mpi,fdr,fbgn,targetid,target_main,query_main,query_name) 

filtered_data_mean<-filtered_data %>% group_by(targetid,query_name) %>% summarise(value=mean(value,na.rm=T))

joined_sub<-filtered_data_mean %>% left_join(interac_sub) %>% as_tibble()

##

  # for an unknown gene 

GI_df<-joined_sub %>% 
  filter(targetid=="01_A14") %>% 
  mutate(significant=if_else(fdr<0.1,if_else(mpi<0,"negative","positive"),"non-significant")) %>%
  dplyr::select(singlemut=query_main,doublemut=value,significant,gene1=query_name,gene2=gene_symbol,fdr,piscore=mpi)

p1 <- ggplot(GI_df) +
  geom_point(data=subset(GI_df,significant=="non-significant"), aes(x=singlemut,y=doublemut,col=significant),pch=19,size=5) + 
  geom_point(data=subset(GI_df,significant!="non-significant"), aes(x=singlemut,y=doublemut,col=significant),pch=19,size=5)+
  geom_smooth(method = "lm",data=GI_df, aes(x=singlemut,y=doublemut),inherit.aes = F,se = F,na.rm=T,col="black")+
  scale_color_manual(values = c("negative"=sgi_blue,"non-significant"=b110_grey,"positive"=sgi_yellow1)) +
  geom_label_repel(data=subset(GI_df,significant!="non-significant"), aes(x=singlemut,y=doublemut,label=gene1),col="black")+
  ylab("double knockdown phenotype") +
  xlab("single knockdown phenotype") + 
  ggtitle(paste0("single vs. double mutant (query gene = ",GI_df$gene2,")")) +
  theme_b110()

 # for Diap1

GI_df<-joined_sub %>% 
  filter(gene_symbol=="Diap1") %>% 
  mutate(significant=if_else(fdr<0.1,if_else(mpi<0,"negative","positive"),"non-significant")) %>%
  dplyr::select(singlemut=query_main,doublemut=value,significant,gene1=query_name,gene2=gene_symbol,fdr,piscore=mpi)

p2 <- ggplot(GI_df) +
  geom_point(data=subset(GI_df,significant=="non-significant"), aes(x=singlemut,y=doublemut,col=significant),pch=19,size=5) + 
  geom_point(data=subset(GI_df,significant!="non-significant"), aes(x=singlemut,y=doublemut,col=significant),pch=19,size=5)+
  geom_smooth(method = "lm",data=GI_df, aes(x=singlemut,y=doublemut),inherit.aes = F,se = F,na.rm=T,col="black")+
  scale_color_manual(values = c("negative"=sgi_blue,"non-significant"=b110_grey,"positive"=sgi_yellow1)) +
  geom_label_repel(data=subset(GI_df,significant!="non-significant"), aes(x=singlemut,y=doublemut,label=gene1),col="black")+
  ylab("double knockdown phenotype") +
  xlab("single knockdown phenotype") + 
  ggtitle(paste0("single vs. double mutant (query gene = ",GI_df$gene2,")")) +
  theme_b110()

GI_df<-joined_sub %>% 
  filter(gene_symbol=="Tor") %>% 
  mutate(significant=if_else(fdr<0.1,if_else(mpi<0,"negative","positive"),"non-significant")) %>%
  dplyr::select(singlemut=query_main,doublemut=value,significant,gene1=query_name,gene2=gene_symbol,fdr,piscore=mpi)

p3 <- ggplot(GI_df) +
  geom_point(data=subset(GI_df,significant=="non-significant"), aes(x=singlemut,y=doublemut,col=significant),pch=19,size=5) + 
  geom_point(data=subset(GI_df,significant!="non-significant"), aes(x=singlemut,y=doublemut,col=significant),pch=19,size=5)+
  geom_smooth(method = "lm",data=GI_df, aes(x=singlemut,y=doublemut),inherit.aes = F,se = F,na.rm=T,col="black")+
  scale_color_manual(values = c("negative"=sgi_blue,"non-significant"=b110_grey,"positive"=sgi_yellow1)) +
  geom_label_repel(data=subset(GI_df,significant!="non-significant"), aes(x=singlemut,y=doublemut,label=gene1),col="black")+
  ylab("double knockdown phenotype") +
  xlab("single knockdown phenotype") + 
  ggtitle(paste0("single vs. double mutant (query gene = ",GI_df$gene2,")")) +
  theme_b110()

p4 <- p1 + p2 +p3 + plot_layout(ncol = 1)

ggsave("plots/Figure_1_C_example_interactions.png",plot = p4,width = 8,height = 12)#)#
```

# Figure 1B feature interaction histograms

```{r}

p1 <- interaction_vecs %>% 
  filter(feature %in% c("cells","actin.m.eccentricity.tmean","tubulin.b.mad.tmean")) %>%
  mutate(grouping=if_else(fdr<0.2,if_else(mpi<0,"sig_neg","sig_pos"),"non_sig")) %>%
  ggplot(aes(mpi,fill=grouping)) + 
  geom_histogram(aes(y=..density..),bins=100)+
  facet_wrap(~feature,scales="fixed") + 
  xlim(-15,15) + 
  theme_b110() + 
  scale_fill_manual(values=c(b110_grey, sgi_blue, sgi_yellow1))

ggsave("plots/Figure_1_B_feature_interaction_histogram.pdf",height = 8,width = 24)
```




